version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    ports: ['9000']
    volumes: ['./:/var/www/symfony']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./:/var/www/symfony']